#!/usr/bin/env zsh

setopt ERR_EXIT
setopt NO_UNSET
setopt PIPE_FAIL

function usage()
{
    cat <<-'EOF'
		Build Party Hat

		Usage:

		    $ build
	EOF
    exit 1
}

if (( $# != 0 )); then
    usage
fi

root=$0:A:h:h
build=$root/local/build

rm --force --recursive $build
cd $root/meteor
meteor build $build --directory
cd $build/bundle/programs/server
npm install

